[WIP] Clean up code style, part 2 of many parts. The prompts folder. #1018
codeforboston/cliff-effects pull request #1021
Opened 2018-11-25 01:59 UTC by knod

2018-11-25 02:52 UTC, knod commented
No longer [WIP]. Probably.

2018-11-28 01:03 UTC, turnerhayes requested changes

2018-11-28 01:03 UTC, turnerhayes commented on src/components/prompts/PredictionsWarning.js
> +class PredictionsWarningComp extends Component {
I'm not a huge fan of the "Comp" suffix; can we just call it `PredictionsWarning`? Or `PredictionsWarningForm` or something?

2018-11-28 01:03 UTC, turnerhayes commented on src/components/prompts/PredictionsWarning.js
> +                onClick = { () => { return this.handleChange(`checkbox1`); } } />
As long as we're cleaning up code, we might as well make these handlers member functions instead of anonymous functions (see #974)

2018-11-28 13:26 UTC, knod commented on src/components/prompts/PredictionsWarning.js
> +class PredictionsWarningComp extends Component {
For that one look at the bottom of the file. `PredictionsWarning` is indeed what's being exported. `PredictionsWarningComp` is being used with `withRouter()` to create `PredictionsWarning`. Can you find another way to express that difference?

2018-11-28 23:07 UTC, turnerhayes commented on src/components/prompts/PredictionsWarning.js
> +class PredictionsWarningComp extends Component {
We could do `export { withRouter(PredictionsWarning) as PredictionsWarning };` (I think that syntax works). Or maybe call it `const WrappedPredictionsWarning = withRouter(PredictionsWarning);` at the bottom and export that with an alias instead, if you don't like inlining the `withRouter()`.

2018-11-29 14:13 UTC, knod commented on src/components/prompts/PredictionsWarning.js
> +class PredictionsWarningComp extends Component {
Hmm, I'm not sure about this aliasing thing. I'm willing to go with that first option for now, but I'm very suspicious.

2018-11-29 14:15 UTC, knod commented on src/components/prompts/PredictionsWarning.js
> +class PredictionsWarningComp extends Component {
Follow-up philosophical question - why the heck can't export syntax just be object syntax? What's up with that?

2018-11-29 14:16 UTC, knod commented on src/components/prompts/PredictionsWarning.js
> +class PredictionsWarningComp extends Component {
Hmm, it doesn't seem to work inline that way. Dang. I really do prefer it that way as opposed to naming it before, but I guess that's a no go.

2018-12-02 00:22 UTC, turnerhayes approved these changes
Looks good!

2018-12-02 01:04 UTC, knod commented on src/components/prompts/PredictionsWarning.js
> +class PredictionsWarningComp extends Component {
@todo Discuss this code style.

2018-12-02 01:04 UTC, merged