Add .nvmrc file. Fixes #931
codeforboston/cliff-effects pull request #979
Opened 2018-11-07 05:09 UTC by turnerhayes

Test plan:

- [Install NVM](https://github.com/creationix/nvm#installation)
- Run `nvm install` from the project root directory
- It should install and use the latest LTS version of Node (at the moment, this is `v10.13.0`)
- Open a new terminal and go to the project directory
- Run `nvm use`
- It should switch to use the LTS version (verify that it is with `node --version`)

2018-11-07 13:02 UTC, knod requested changes

2018-11-07 13:02 UTC, knod commented on .nvmrc
> +lts/*
Hmm, I think [we](https://github.com/codeforboston/cliff-effects/pull/824#issuecomment-426595109) wanted to specify an actual version number. Would that be acceptable?

2018-11-07 13:03 UTC, knod commented
Also, is there a way to add a pre-... `npm install` hook to make sure this happens for new folks right off?

2018-11-08 03:21 UTC, turnerhayes commented on .nvmrc
> +lts/*
Ah, missed that comment. Will fix!

2018-11-08 20:42 UTC, turnerhayes commented
That might be trickier, because it depends on `nvm` being installed, and as far as I know there's not a good way to do that from a script--I think they will have to install nvm first (if they don't have it).

*Maybe* there's a way to detect if `nvm` is installed and run the necessary commands only in that case?

2018-11-08 20:44 UTC, knod commented
Dang, forgot about that part. Hmm. Maybe a warning if they're using the wrong version of node/npm?

2018-11-08 23:38 UTC, turnerhayes commented
That can be done; the problem is that `create-react-app`'s `start` script clears the console, so at most you'd see the warning appear for a couple of seconds and that might not be enough to register it.

2018-11-09 13:22 UTC, knod commented
I was actually thinking of doing it at other times. For example, when they first clone the repo, when they do `npm install`, when they push. It seems like there's a lot of different options.

2018-11-09 13:23 UTC, knod approved these changes
Sorry, didn't see this change! The discussion about a script to warn folks can happen elsewhere. @todo!

2018-11-11 00:04 UTC, merged